export const FEATURES = {
  CODING_PLATFORM_INTEGRATION: true,
  UNIVERSAL_TIME_TRACKER: true,
  MONEY_METER: true,
  NOTIFICATION_BANNERS: true,
  URL_BLOCKER: true,
  WEEKLY_REPORTS: true,
  SMART_SUGGESTIONS: true,
  MASCOT_COMPANION: true,
};
